### ISSUE TITLE
Informations 

### ISSUE THREAD

**Issue by pierrbt** [MateuszJanda/rdest#1]
@MateuszJanda 
Hello, I want to create a game launcher using torrents to download games. Can you give me more information about the library.

Multi peers ?
Multi files ?
Efficient ?
Usage of magnet link or torrent string ?
Progress % and speed ?
End download alert ?
Support large torrents (100G) ?
Download resume (optional)

If you think this library isn't enough for this usage, what others library can I use ?

**Comment by MateuszJanda** [comment]
Multi peers ? - Yes, but not configurable.
Multi files ? - Yes, but I don't remember if tree directory is supported.
Efficient ? - ?
Usage of magnet link or torrent string ? - Nope.
Progress % and speed ? - Only chunk counting.
End download alert ? - Nope, client just exit.
Support large torrents (100G) ? - Should work, but never tested.
Download resume (optional) - Nope.

If you think this library isn't enough for this usage, what others library can I use ? - libtorrent
